### ISSUE TITLE
App is not working in LG G5 phone.

### ISSUE THREAD

**Issue by manusp105** [square/in-app-payments-android-quickstart#16]
Getting crash in LG phone when the buy button in the app clicked and select the new card button.

please find the below crash report.

02-25 12:56:00.931 E/ReportHandler( 8557): FATAL EXCEPTION: main
02-25 12:56:00.931 E/ReportHandler( 8557): java.lang.RuntimeException: Unable to start activity ComponentInfo{xxx.xxx.xxx/sqip.internal.CardEntryActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class android.widget.ProgressBar
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.app.ActivityThread.access$900(ActivityThread.java:157)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.os.Looper.loop(Looper.java:148)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.app.ActivityThread.main(ActivityThread.java:5551)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at java.lang.reflect.Method.invoke(Native Method)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
02-25 12:56:00.931 E/ReportHandler( 8557): Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class android.widget.ProgressBar
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at sqip.internal.CardEntryActivity.onCreate(CardEntryActivity.kt:128)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.app.Activity.performCreate(Activity.java:6272)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
02-25 12:56:00.931 E/ReportHandler( 8557): 	... 9 more
02-25 12:56:00.931 E/ReportHandler( 8557): Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class android.widget.ProgressBar
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
02-25 12:56:00.931 E/ReportHandler( 8557): 	... 17 more
02-25 12:56:00.931 E/ReportHandler( 8557): Caused by: java.lang.reflect.InvocationTargetException
02-25 12:56:00.931 E/ReportHandler( 8557): 	at java.lang.reflect.Constructor.newInstance(Native Method)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
02-25 12:56:00.931 E/ReportHandler( 8557): 	... 24 more
02-25 12:56:00.931 E/ReportHandler( 8557): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/sqip_loader_spinner.xml from drawable resource ID #0x7f080222
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2748)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.content.res.Resources.loadDrawable(Resources.java:2643)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.widget.ProgressBar.<init>(ProgressBar.java:311)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.widget.ProgressBar.<init>(ProgressBar.java:255)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.widget.ProgressBar.<init>(ProgressBar.java:251)
02-25 12:56:00.931 E/ReportHandler( 8557): 	... 26 more
02-25 12:56:00.931 E/ReportHandler( 8557): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/sqip_loader_progress.xml from drawable resource ID #0x7f080221
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2748)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.content.res.Resources.loadDrawable(Resources.java:2643)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:296)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:239)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:164)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
02-25 12:56:00.931 E/ReportHandler( 8557): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2733)
02-25 12:56:00.931 E/ReportHandler( 8557): 	... 31 mor

**Comment by StephenJosey** [comment]
Hey @manusp105 thanks for reporting. So we can dig into this, can you provide a few things:

- What version of In-App Payments SDK are you using?
- What Android version is running on your LG G5?

**Comment by manusp105** [comment]
Hi,

implementation "com.squareup.sdk.in-app-payments:card-entry: 1.2.0"
Android version 6.0

**Comment by StephenJosey** [comment]
Would you be able to update to the latest (1.3.0) to see if it resolves your issue? This sounds similar to https://github.com/square/in-app-payments-flutter-plugin/issues/50#issuecomment-590702498 which was resolved in 1.2.2. Please let me know if that doesn't work, though.

**Comment by manusp105** [comment]
Issue still exists, getting the same crash report.

02-27 07:11:56.243 E/AndroidRuntime(24337): FATAL EXCEPTION: main
02-27 07:11:56.243 E/AndroidRuntime(24337): Process: com.example.supercookie, PID: 24337
02-27 07:11:56.243 E/AndroidRuntime(24337): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.supercookie/sqip.internal.CardEntryActivity}: android.view.InflateException: Binary XML file line #76: Binary XML file line #76: Error inflating class android.widget.ProgressBar
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2434)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2494)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.app.ActivityThread.access$900(ActivityThread.java:157)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.os.Looper.loop(Looper.java:148)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.app.ActivityThread.main(ActivityThread.java:5551)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at java.lang.reflect.Method.invoke(Native Method)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:730)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:620)
02-27 07:11:56.243 E/AndroidRuntime(24337): Caused by: android.view.InflateException: Binary XML file line #76: Binary XML file line #76: Error inflating class android.widget.ProgressBar
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at sqip.internal.CardEntryActivity.onCreate(CardEntryActivity.kt:128)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.app.Activity.performCreate(Activity.java:6272)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2387)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	... 9 more
02-27 07:11:56.243 E/AndroidRuntime(24337): Caused by: android.view.InflateException: Binary XML file line #76: Error inflating class android.widget.ProgressBar
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:694)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:762)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	... 17 more
02-27 07:11:56.243 E/AndroidRuntime(24337): Caused by: java.lang.reflect.InvocationTargetException
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at java.lang.reflect.Constructor.newInstance(Native Method)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	... 24 more
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2748)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.content.res.Resources.loadDrawable(Resources.java:2643)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.widget.ProgressBar.<init>(ProgressBar.java:311)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.widget.ProgressBar.<init>(ProgressBar.java:255)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.widget.ProgressBar.<init>(ProgressBar.java:251)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	... 26 more
02-27 07:11:56.243 E/AndroidRuntime(24337): Caused by: android.content.res.Resources$NotFoundException: File res/drawable/sqip_loader_progress.xml from drawable resource ID #0x7f0700c8
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.content.res.Resources.loadDrawableForCookie(Resources.java:2748)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.content.res.Resources.loadDrawable(Resources.java:2643)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.content.res.TypedArray.getDrawable(TypedArray.java:870)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.graphics.drawable.LayerDrawable.updateLayerFromTypedArray(LayerDrawable.java:296)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.graphics.drawable.LayerDrawable.inflateLayers(LayerDrawable.java:239)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.graphics.drawable.LayerDrawable.inflate(LayerDrawable.java:164)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:1215)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:1124)
02-27 07:11:56.243 E/AndroidRuntime(24337): 	at android.content.res.Resources.l

**Comment by StephenJosey** [comment]
Thanks for sharing. I'll report to our Android team and follow-up once we have more information.

**Comment by StephenJosey** [comment]
Have you changed anything else in the quickstart? Are you able to run it in a simulator successfully? I'm currently testing with android simulators and not able to replicate.

**Comment by manusp105** [comment]
> Thanks for sharing. I'll report to our Android team and follow-up once we have more information. **Edit**: actually, could you please share your application id here so we can look up logs if needed?

The same sample application is not working in LG phone in other phones it is working fine.
Application ID : com.example.supercookie

**Comment by manusp105** [comment]
> Have you changed anything else in the quickstart? Are you able to run it in a simulator successfully? I'm currently testing with android simulators and not able to replicate.

I have not changed anything just imported the project and generated the APK

**Comment by manusp105** [comment]
We found the issue. This relates to https://stackoverflow.com/questions/47783045/gradient-tag-inside-xml-causes-android-to-crash. 
Please move this sqip_loader_circle.xml to drawable-v24 folder.

**Comment by StephenJosey** [comment]
Sorry for the delay here. I'm glad you were able to figure it out, and thank you so much for sharing the solution here.

**Comment by manusp105** [comment]
> Sorry for the delay here. I'm glad you were able to figure it out, and thank you so much for sharing the solution here.

Issue still exists can you please update and release the new version?
